- name: Build the api image if not exists
  shell:
    cmd: docker images -q my_flask | grep -q . || docker build -t my_flask ./roles/api/files/


- name: Build the api container if not exists
  shell:
    cmd: docker inspect flask_app >/dev/null 2>&1 || docker run -d --name flask_app --network mongodb_flask_nginx_network my_flask