- name: Build the nginx image if not exists
  shell:
    cmd: docker images -q my_nginx | grep -q . || docker build -t my_nginx ./roles/web/files/


- name: Build the Nginx container if not exists
  shell:
    cmd: docker inspect nginx_container >/dev/null 2>&1 || docker run -d -p 80:80 --name nginx_container --link flask_app:flask --network mongodb_flask_nginx_network my_nginx 

- name: Start these containers if you restart your os
  shell:
    cmd: docker start mongodb-server flask_app nginx_container

- name: Open localhost
  shell:
    cmd: curl localhost 